### ISSUE TITLE
Ubuntu 18.04 设置静态ip方法

### ISSUE THREAD

**Issue by zazitufu** [zazitufu/ubuntu#1]
1，先查看配置的网卡ID和当前的IP
`ifconfig`
![image](https://user-images.githubusercontent.com/57139031/84532052-259ba880-ad18-11ea-9918-ed0826706684.png)
注意上面截图的画圈位置。

2、查看子网掩码写法
`ip a`
![image](https://user-images.githubusercontent.com/57139031/84532275-8925d600-ad18-11ea-8c5d-55d5f0804d42.png)

3、编辑配置文件
`nano /etc/netplan/01-netcfg.yaml`
下面内容填上，其中【addresses】字段参考上面第2步截图内容
```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses: [192.168.137.10/24]
      gateway4: 192.168.137.1
      nameservers:
         addresses: [192.168.137.1,192.168.123.1,223.5.5.5]
```
保存并退出

4、应用变更内容
`sudo netplan apply`

**Comment by zazitufu** [comment]
如果要恢复动态IP，将此文件删掉，再运行一次
`sudo netplan apply`

**Comment by zazitufu** [comment]
不要修改这个文件
`cat /etc/netplan/50-cloud-init.yaml`

```
#如果在 Netplan 上使用 DHCP，配置文件看起来就像这样：
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    ethernets:
        eno1:
            dhcp4: true
    version: 2
```
参考文档：
https://askubuntu.com/questions/1029531/how-to-setup-a-static-ip-on-ubuntu-server-18-04
